export const projects = [
  {
    title: 'React admin dashboard',
    description: "An admin dashboard to manage customer details create, udate and delete customer info and also update products and see charts, soon there will be an update to have a firebase database to have more secure and better logs.",
    tags: ['React', 'Firebase', 'Node'],
    source: 'https://watch-tower.netlify.app',
    visit: 'https://watch-tower.netlify.app',
    id: 0,
  },
  {
    title: 'Track.Io',
    description: "A demo project for a online school, similar to skill share",
    tags: ['React', 'JavaScript', 'Node'],
    source: 'https://track-io.netlify.app/',
    visit: 'https://track-io.netlify.app/',
    id: 1,
  },
  {
    title: 'Harry Foundation',
    description: "A progress web application built for an NGO with e-commerce functionality as well improved security",
    tags: ['React', 'JavaScript', 'Node'],
    source: 'https://harryfoundation.co',
    visit: 'https://harryfoundation.co',
    id: 1,
  },
  {
    title: 'Corona Virus Tracker',
    description: "Fully Responsive Tracker, Can get Info and stats on the Corona Virus Anywhere in the world",
    tags: ['React', 'Node'],
    source: 'https://corona-virustrack.netlify.app',
    visit: 'https://corona-virustrack.netlify.app',
    id: 2,
  },
  {
    title: 'Virus Rampage',
    description: "A 2D game based on shooting viruses from space",
    tags: ['HTML5', 'JS', 'Game Maker'],
    source: 'https://virus-rampage.netlify.app',
    visit: 'https://virus-rampage.netlify.app',
    id: 3,
  },
  {
    title: 'Tasty Stuff',
    description: "A full blown resturant application with darkmode and smooth functionality",
    tags: ['HTML5', 'JS', 'CSS'],
    source: 'https://tastystuff.netlify.app',
    visit: 'https://tastystuff.netlify.app',
    id: 3,
  },
  {
    title: 'Coffee landing page',
    description: "coffee landing page",
    tags: ['HTML5', 'JS', 'CSS'],
    source: 'https://solder-mint-dapp.vercel.app',
    visit: 'https://solder-mint-dapp.vercel.app',
    id: 3,
  },
  {
    title: 'Minting site clone',
    description: "NFT minting site cloned and contract built, to show proficiecy in blockchain development and engineering",
    tags: ['HTML5', 'JS', 'CSS'],
    source: 'https://cafestorm.netlify.app',
    visit: 'https://cafestorm.netlify.app',
    id: 3,
  },
  {
    title: 'Pride VR',
    description: "Virtual Realty startup site built on React",
    tags: ['HTML5', 'JS', 'CSS', 'Blockchain'],
    source: 'https://pride-vr.netlify.app/',
    visit: 'https://pride-vr.netlify.app/',
    id: 3,
  },
  {
    title: 'CIV Journal',
    description: "Journal built on gatsby to document your christian journey or basically any journey",
    tags: ['HTML5', 'JS', 'CSS', 'Blockchain'],
    source: 'https://civ-journal.netlify.app/',
    visit: 'https://civ-journal.netlify.app/',
    id: 3,
  },

];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey as a  Developer In High School', },
  { year: 2018, text: 'Worked as a freelance developer, developing my self and working on projects', },
  { year: 2019, text: 'Worked With My First Firm', },
  { year: 2020, text: 'Got into robotics and aero-dynamics', },
  { year: 2021, text: 'Started my own tech firm, been making amazing things and meeting great people', },
  { year: 2022, text: 'Currently on my python grind building 3D animation and motion graphics tools, well as full stack developer', },
];